import { COMMANDS, GROUPS, isBare, type CommandSpec } from "./commands.ts";
import { SELECTOR_PROPS } from "./primitives.ts";
import { buildFlowSchema, buildGateSchema, buildRegistrySchema } from "./schemas.ts";

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const code = (value: string) => `\`${value}\``;

function keysOf(spec: CommandSpec): string {
  const names = Object.keys(spec.props);
  const selector = Object.keys(SELECTOR_PROPS).every(key => names.includes(key));
  const listed = names.filter(name => !selector || !(name in SELECTOR_PROPS)).map(name => code(name) + (spec.required?.includes(name) ? "*" : ""));
  const alternatives = (spec.rule?.anyOf ?? spec.rule?.oneOf) as Array<{ required: string[] }> | undefined;
  const choices = alternatives?.map(branch => branch.required[0]!) ?? [];
  const quantity = spec.rule?.oneOf ? "exactly one" : "at least one";
  const rule = !choices.length || selector ? "" : choices.length === names.length ? ` (${quantity})` : `; ${quantity} of ${choices.map(code).join(", ")}`;
  return [selector && "any selector", ...listed].filter(Boolean).join(", ") + rule || "—";
}

function reference(): string {
  const lines = [
    "<!-- Generated by `bun run e2e:schema` from scripts/e2e/format/commands.ts. Do not edit by hand. -->",
    "# E2E flow command reference",
    "",
    "How to write and check flows: [e2e-flows.md](e2e-flows.md). Every command's mapping form also takes `when` and `timeout`.",
    "",
    "- **Short form**: `bare` means the command can stand alone (`- launchApp`); `value → key` means `- cmd: value` is `- cmd: { key: value }`.",
    "- **Keys**: `*` = required. `any selector` = the selector keys (`id`, `role`, `label`, `text`, `within`, `index`, `window`, `below`, `above`, `leftOf`, `rightOf`, `point`); a bare string is visible text.",
    "- **driver**: needs the Spark in-app driver (white-box). Everything else is black-box (OS input + accessibility tree).",
    "- **maestro**: Maestro core command; keeps Maestro semantics.",
  ];
  for (const [group, title] of Object.entries(GROUPS)) {
    lines.push("", `## ${title}`, "", "| Command | Short form | Keys | Backend | Summary |", "|---|---|---|---|---|");
    for (const [name, spec] of Object.entries(COMMANDS).filter(([, spec]) => spec.group === group)) {
      const short = [isBare(spec) && "bare", spec.shorthand && `value → ${code(spec.shorthand)}`].filter(Boolean).join(", ") || "—";
      const backend = [spec.driver ? "driver" : "black-box", spec.maestro && "maestro"].filter(Boolean).join(", ");
      lines.push(`| ${code(name)} | ${short} | ${keysOf(spec)} | ${backend} | ${spec.summary.replace(/\|/g, "\\|")} |`);
    }
  }
  return `${lines.join("\n")}\n`;
}

/** Every checked-in file generated from the command catalog, by repository path. A test fails when one drifts. */
export function generatedFiles(): Record<string, string> {
  return {
    "e2e/schema/flow.schema.json": json(buildFlowSchema()),
    "e2e/schema/checks.schema.json": json(buildRegistrySchema()),
    "e2e/schema/gate.schema.json": json(buildGateSchema()),
    "docs/e2e-flow-commands.md": reference(),
  };
}
