// One entry per release-gate epic. `id` is the area folder used by
// e2e/checks/<id>.yaml, e2e/flows/<id>/ and screens/<id>/. Titles are localized in shell/i18n.ts.
export const AREAS = [
  { id: "infra", prefix: "INFRA" },
  { id: "app-lifecycle", prefix: "LIFE" },
  { id: "windows", prefix: "WIN" },
  { id: "toolbar-title-bar", prefix: "TBAR" },
  { id: "menus", prefix: "MENU" },
  { id: "keyboard", prefix: "KEY" },
  { id: "pointer-trackpad", prefix: "PTR" },
  { id: "text-input-editing", prefix: "TEXT" },
  { id: "native-controls", prefix: "CTRL" },
  { id: "appearance-theming", prefix: "APPR" },
  { id: "displays-graphics", prefix: "DISP" },
  { id: "files-filesystem", prefix: "FILE" },
  { id: "dialogs", prefix: "DLG" },
  { id: "document-model", prefix: "DOC" },
  { id: "clipboard", prefix: "CLIP" },
  { id: "drag-drop", prefix: "DND" },
  { id: "notifications", prefix: "NOTIF" },
  { id: "system-integration", prefix: "SYS" },
  { id: "media", prefix: "MEDIA" },
  { id: "networking-webview", prefix: "WEB" },
  { id: "processes-ipc", prefix: "PROC" },
  { id: "storage-data", prefix: "DATA" },
  { id: "authentication", prefix: "AUTH" },
  { id: "updates", prefix: "UPD" },
  { id: "packaging-distribution", prefix: "DIST" },
  { id: "accessibility", prefix: "A11Y" },
  { id: "internationalization", prefix: "I18N" },
  { id: "performance-budgets", prefix: "PERF" },
  { id: "reliability-diagnostics", prefix: "REL" },
  { id: "security", prefix: "SEC" },
  { id: "developer-experience", prefix: "DX" },
  { id: "edge-abuse-cases", prefix: "EDGE" },
  { id: "motion-system", prefix: "MOT" },
  { id: "flourishes-micro-interactions", prefix: "FLR" },
  { id: "multiwindow", prefix: "MW" },
  { id: "component-library", prefix: "COMP" },
  { id: "future-facing-capabilities", prefix: "FUT" },
] as const;

export type AreaId = (typeof AREAS)[number]["id"];
export type Area = (typeof AREAS)[number];
