const { validateOwned, validatePlatforms } = require("./validation.cjs");
const fs = require("node:fs");
const path = require("node:path");
const { createHash } = require("node:crypto");
const { validateWindow } = require("@legendapp/spark-window-options");
const { identity } = require("./identity.cjs");
const filename = "desktop.config.json";
const managedConfig = "// Generated by spark: universal Expo configuration";
function isExpoProject(root) {
  const file = path.join(root, filename);
  return fs.existsSync(file) && JSON.parse(fs.readFileSync(file, "utf8")).extends === "expo";
}
function isUniversal(root) {
  const file = path.join(root, filename);
  return fs.existsSync(file) && (JSON.parse(fs.readFileSync(file, "utf8")).platforms?.length ?? 1) > 1;
}
function statePath(root, name, target = process.env.SPARK_PLATFORM) {
  if (!isUniversal(root)) return path.join(root, ".spark", name);
  const value = JSON.parse(fs.readFileSync(path.join(root, filename), "utf8"));
  target = selectTarget(value.platforms, target);
  return path.join(root, ".spark", "platforms", target, name);
}
function selectTarget(platforms, target) {
  validatePlatforms(platforms);
  const selected = target ?? (platforms.includes(process.platform === "win32" ? "windows" : "macos") ? (process.platform === "win32" ? "windows" : "macos") : platforms[0]);
  if (!platforms.includes(selected)) throw new Error(`Platform ${selected} is not supported by this project`);
  return selected;
}
function readConfig(root, target = process.env.SPARK_PLATFORM) {
  const file = path.join(root, filename);
  if (isExpoProject(root)) {
    const value = JSON.parse(fs.readFileSync(file, "utf8"));
    const selected = selectTarget(value.platforms, target);
    const previous = process.env.SPARK_PLATFORM;
    try {
      process.env.SPARK_PLATFORM = selected;
      // Resolve Expo's own reader from the application's installed Expo version.
      const { createRequire } = require("node:module");
      const appRequire = createRequire(path.join(root, "package.json"));
      const expoRequire = createRequire(appRequire.resolve("expo/package.json"));
      const { getConfig } = expoRequire("@expo/config");
      // Expo's reader metadata contains absolute config paths, not app settings.
      // Keep it out of native compatibility signatures (e.g. /tmp vs /private/tmp).
      const { _internal, ...expo } = getConfig(root, { skipPlugins: true }).exp;
      if (["macos", "windows"].includes(selected) && expo.extra?.spark?.projectId !== value.projectId) throw new Error("Compose app.config with withSparkExpo before running desktop commands");
      return { expo: { ...expo, platforms: [selected] } };
    } finally {
      if (previous === undefined) delete process.env.SPARK_PLATFORM; else process.env.SPARK_PLATFORM = previous;
    }
  }
  if (!fs.existsSync(file)) {
    const value = JSON.parse(fs.readFileSync(path.join(root, "app.json"), "utf8"));
    if (!value?.expo || typeof value.expo !== "object" || Array.isArray(value.expo)) throw new Error("app.json needs an expo configuration object");
    return { ...value, expo: { ...value.expo, platforms: validatePlatforms(value.expo.platforms ?? ["macos"]) } };
  }
  const result = toExpo(JSON.parse(fs.readFileSync(file, "utf8")), target);
  return result;
}
function supportedPlatforms(root) {
  const file = path.join(root, filename);
  if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file, "utf8")).platforms ?? ["macos"];
  return readConfig(root).expo.platforms ?? ["ios", "android", "web"];
}
// A live server has no single build target. Platform build overlays (notably
// native autolinking exclusions) must not leak into other platforms' JS graphs.
function developmentConfig(value, target) {
  const result = toExpo({ ...value, expoByPlatform: {} }, target).expo;
  result.platforms = value.platforms ?? ["macos"];
  return result;
}
function expoConfig(root) {
  if (process.env.SPARK_DEV_SESSION === "1") {
    return developmentConfig(JSON.parse(fs.readFileSync(path.join(root, filename), "utf8")), process.env.SPARK_PLATFORM);
  }
  const result = readConfig(root);
  return applySelection(root, result.expo);
}
function applySelection(root, expo) {
  if (isUniversal(root)) {
    const selection = statePath(root, "native-selection.json", expo.platforms[0]);
    if (expo.platforms[0] === "macos" && fs.existsSync(selection)) {
      const excluded = JSON.parse(fs.readFileSync(selection, "utf8")).excluded ?? [];
      expo.autolinking = { ...expo.autolinking, exclude: [...new Set([...(expo.autolinking?.exclude ?? []), ...excluded])] };
    }
  }
  return expo;
}
function toExpo(value, target) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Desktop config must be an object");
  const allowed = ["$schema", "name", "projectId", "version", "window", "macos", "platforms", "scheme", "documentTypes", "menuBarOnly", "updates", "include", "signing", "helpers", "expo", "expoByPlatform"];
  for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`Unknown desktop configuration field: ${key}`);
  for (const key of ["name", "projectId", "version"]) if (typeof value[key] !== "string" || !value[key].trim()) throw new Error(`Desktop config needs ${key}`);
  const platforms = value.platforms ?? ["macos"];
  validatePlatforms(platforms);
  validateOwned(value);
  const selected = selectTarget(platforms, target);
  if (platforms.includes("macos") && (!value.macos || typeof value.macos.bundleIdentifier !== "string" || !/^[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$/.test(value.macos.bundleIdentifier))) throw new Error("macos.bundleIdentifier must be a reverse-DNS identifier");
  validateWindow(value.window ?? {});
  if (value.include !== undefined && (!Array.isArray(value.include) || value.include.some(x => typeof x !== "string"))) throw new Error("include must be a list of package names");
  require("./helpers.cjs").validateHelpers(value.helpers);
  const extra = { projectId: value.projectId };
  for (const key of ["window", "documentTypes", "menuBarOnly", "updates", "include", "signing", "helpers"]) if (value[key] !== undefined) extra[key] = value[key];
  const overrides = value.expoByPlatform ?? {};
  if (!overrides || typeof overrides !== "object" || Array.isArray(overrides) || Object.keys(overrides).some(p => !platforms.includes(p))) throw new Error("expoByPlatform keys must be supported platforms");
  const backend = merge(value.expo ?? {}, overrides[selected] ?? {});
  if (!backend || typeof backend !== "object" || Array.isArray(backend)) throw new Error("expo overrides must be an object");
  const hex = createHash("sha256").update(value.projectId).digest("hex");
  const guid = `${hex.slice(0,8)}-${hex.slice(8,12)}-5${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`;
  const config = {
    ...backend,
    name: value.name, slug: backend.slug ?? value.name.toLowerCase().replace(/[^a-z0-9-]/g, "-"), version: value.version,
    platforms: [selected], newArchEnabled: true,
    ...(value.macos ? { macos: { ...value.macos, infoPlist: { CFBundleName: value.name, ...value.macos.infoPlist } } } : {}),
    ...(value.scheme !== undefined ? { scheme: value.scheme } : {}),
    extra: { ...backend.extra, spark: { ...extra, ...(platforms.length > 1 ? { supportedPlatforms: platforms } : {}) } },
    // SDK 58 enables autolinking module resolution for out-of-tree targets; it loads every
    // dependency's react-native.config.js (react-native-windows' throws off Windows) and
    // duplicates the desktop Metro remapping. Keep SDK 54's opt-in default for desktop targets.
    experiments: { ...(["macos", "windows"].includes(selected) ? { autolinkingModuleResolution: false } : {}), ...backend.experiments, outOfTreePlatforms: true },
    windows: backend.windows ?? { namespace: "DesktopApp", displayName: value.name, packageGuid: guid, projectGuid: guid },
    plugins: [...(["macos", "windows"].includes(selected) ? ["@legendapp/spark/config-plugin"] : []), ...(backend.plugins ?? []).filter(p => (Array.isArray(p) ? p[0] : p) !== "@legendapp/spark-desktop-config" && (Array.isArray(p) ? p[0] : p) !== "@legendapp/spark/config-plugin")],
  };
  const nativeIdentity = identity(config);
  // Materialize the framework-owned associations before Expo's base mods run.
  // This also avoids the desktop backend's broken array-valued scheme coercion.
  if (selected === "macos" && nativeIdentity.CFBundleURLTypes) {
    config.macos.infoPlist.CFBundleURLTypes = nativeIdentity.CFBundleURLTypes;
  }
  return { expo: config };
}
function merge(base, override) {
  if (!base || typeof base !== "object" || Array.isArray(base) || !override || typeof override !== "object" || Array.isArray(override)) throw new Error("Expo overrides must be objects");
  const result = { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (["__proto__", "constructor", "prototype"].includes(key)) throw new Error("Invalid Expo override key");
    result[key] = value && typeof value === "object" && !Array.isArray(value) && result[key] && typeof result[key] === "object" && !Array.isArray(result[key]) ? merge(result[key], value) : value;
  }
  return result;
}
// Expo tools read this generated transport file. All framework consumers resolve
// the canonical source; the generated file is never edited by SDK commands.
function prepareConfig(root) {
  if (isExpoProject(root)) return readConfig(root);
  if (isUniversal(root)) {
    const file = path.join(root, "app.config.js");
    if (fs.existsSync(path.join(root, "app.config.ts")) || (fs.existsSync(file) && !fs.readFileSync(file, "utf8").startsWith(managedConfig))) throw new Error("Universal configuration needs a spark-managed app.config.js; preserve custom configuration under expo or expoByPlatform");
    const result = readConfig(root);
    if (!fs.existsSync(file)) fs.writeFileSync(file, `${managedConfig}\nmodule.exports = () => require("@legendapp/spark/config").expoConfig(__dirname);\n`);
    return result;
  }
  if (fs.existsSync(path.join(root, filename)) && ["app.config.js", "app.config.ts"].some(name => fs.existsSync(path.join(root, name)))) throw new Error("desktop.config.json cannot be combined with an Expo app.config file; put backend overrides under expo in desktop.config.json");
  const result = readConfig(root);
  if (fs.existsSync(path.join(root, filename))) {
    const file = path.join(root, "app.json");
    const content = JSON.stringify(result, null, 2) + "\n";
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
      const temporary = `${file}.${process.pid}.tmp`;
      fs.writeFileSync(temporary, content); fs.renameSync(temporary, file);
    }
  }
  return result;
}
function writeUpdates(root, updates) {
  require("./updates.cjs").updateConfiguration({ extra: { spark: { updates } } });
  const file = path.join(root, filename);
  if (fs.existsSync(file)) {
    const value = JSON.parse(fs.readFileSync(file, "utf8")); value.updates = updates;
    if (value.extends !== "expo") toExpo(value);
    const temporary = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(temporary, JSON.stringify(value, null, 2) + "\n"); fs.renameSync(temporary, file);
  } else {
    const value = readConfig(root); value.expo.extra ??= {}; value.expo.extra.spark ??= {}; value.expo.extra.spark.updates = updates;
    const target = path.join(root, "app.json"); const temporary = `${target}.${process.pid}.tmp`;
    fs.writeFileSync(temporary, JSON.stringify(value, null, 2) + "\n"); fs.renameSync(temporary, target);
  }
}
module.exports = { readConfig, toExpo, prepareConfig, writeUpdates, statePath, isUniversal, isExpoProject, selectTarget, expoConfig, applySelection, supportedPlatforms, developmentConfig };
