import { packageManager, managerCommand } from "../packages/cli/src/package-manager.ts";
// Create a standalone desktop consumer and compile its app-owned helper.
import { cpSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import { windowsArchitecture } from "../packages/cli/src/platform.ts";
import { create } from "../packages/cli/src/create.ts";
import { run } from "../packages/cli/src/commands.ts";
import { readJson, writeJson } from "../packages/cli/src/project.ts";
const framework = path.resolve(import.meta.dirname, "..");
const root = path.resolve(process.argv[2] ?? ".spark/examples/HelperDemo");
if (existsSync(root)) throw Error("Choose a fresh destination; this script does not overwrite apps.");
if (process.platform !== "darwin" && process.platform !== "win32") throw Error("Create this desktop example on macOS or Windows.");
const arch = process.platform === "win32" ? windowsArchitecture() : process.arch;
if (!['arm64', 'x64'].includes(arch) || (process.platform === 'darwin' && arch !== 'arm64')) throw Error('Unsupported desktop architecture');
if (process.platform === 'win32' && process.env.VSCMD_ARG_TGT_ARCH !== arch) throw Error(`Use a Visual Studio developer shell targeting ${arch}.`);
const platform = process.platform === "darwin" ? "macos" : "windows", target = `${platform}-${arch}`;
const manifest = path.join(framework, "artifacts/packages/manifest.json");
if (!existsSync(manifest)) throw Error("Run bun run pack:local first.");
await create(root, manifest, platform);
for (const file of ["App.tsx", "client.ts", "service.ts"]) cpSync(path.join(framework, "examples/sidecar", file), path.join(root, file));
const directory = path.join(root, "helpers/worker/binaries", target); mkdirSync(directory, { recursive: true });
cpSync(path.join(framework, "examples/sidecar/worker.c"), path.join(root, "helpers/worker/worker.c"));
const executable = platform === "macos" ? "worker" : "worker.exe";
await run(directory, platform === "macos" ? ["cc", "../../worker.c", "-o", executable] : ["cl.exe", "/O2", "/MT", "../../worker.c", `/Fe:${executable}`]);
const pkg = readJson(path.join(root, "package.json")); pkg.dependencies["base64-js"] = "1.5.1"; writeJson(path.join(root, "package.json"), pkg);
const config = readJson(path.join(root, "desktop.config.json"));
config.helpers = { worker: { [target]: { directory: `helpers/worker/binaries/${target}`, executable } } };
writeJson(path.join(root, "desktop.config.json"), config);
await run(root, managerCommand(packageManager(root), ["install"]));
await run(root, ["node", "node_modules/typescript/bin/tsc", "--noEmit"]);
console.log(`Ready: ${root}\nRun npm run ${platform} there, then choose Build for the custom helper runtime.`);
